version: '3'
services:
  db:
    container_name: restowaves-tt-db-dev
    image: postgres:alpine
    restart: always
    expose:
      - '5432'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=ttdb
    volumes:
      - ./volumes/postgres-dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5